### PR TITLE
adjust toc depth

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 22 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-297f4e313/docs/portal-onboarding-guide/). valid for 14 days

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 23 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-297f4e313/docs/portal-onboarding-guide/). valid for 14 days

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by Sterling463** [comment]
build me

**Comment by rackernexus** [comment]
Build 24 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-297f4e313/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 25 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-297f4e313/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 26 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-297f4e313/docs/portal-onboarding-guide/). valid for 14 days

**Pull request merged**
