### PR TITLE
github issues

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 28 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-955990588/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 29 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-54f7b311b/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 30 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-48a54aed9/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 31 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-976f8ca99/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 32 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-6d13797c9/docs/portal-onboarding-guide/). valid for 14 days

**Review by viridaria — APPROVED** [review]

**Pull request merged**
