### PR TITLE
Netlify Setup

### PR DESCRIPTION
**Pull request by ravivalluri**

### CODE REVIEW

**Comment by WilliamLoy** [comment]
build me

**Comment by rackernexus** [comment]
Build 67 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-92b2f49b0/docs/portal-onboarding-guide/). valid for 14 days

**Comment by ravivalluri** [comment]
build me

**Comment by rackernexus** [comment]
Build 68 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-92b2f49b0/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 69 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-6a44728ac/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 70 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-9be8fb6e7/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 71 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-05ccf7420/docs/portal-onboarding-guide/). valid for 14 days

**Pull request merged**
