### PR TITLE
account switcher draft

### PR DESCRIPTION
**Pull request by Sterling463**

### CODE REVIEW

**Comment by rackernexus** [comment]
Build 72 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-656d4427a/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 74 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-43f46b97f/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 76 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-bab08d463/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 77 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-30bf8c436/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 78 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-018a610fd/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 80 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-d2ab76db5/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 81 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-ed622f7a6/docs/portal-onboarding-guide/). valid for 14 days

**Comment by rackernexus** [comment]
Build 82 was successful. Staging content [Preview!](https://developer-revs.staging.deconst.org/build-0d1443c42/docs/portal-onboarding-guide/). valid for 14 days

**Comment by catlook** [comment]
I'll edit these tomorrow, Chad!

**Comment by catlook** [comment]
@Sterling463, review my edits and see if you agree :)

**Review by catlook — APPROVED** [review]
LGTM (note I didn't test the links)

**Review by cal27279 — APPROVED** [review]
lgtm!

**Pull request merged**
